#lang planet neil/sicp
(define (cont-frac n d k)
  (define (loop result term)
    (if (= term 0)
        result
        (loop (/ (n term)
                 (+ (d term) result))
              (- term 1))))
  (loop 0 k))
(define (tan x k)
  (cont-frac (lambda (i)
               (if (= i 1) x (* x x)))
             (lambda (i)
               (- (* i 2) 1))
             k))
(tan 1 1000)